spring:
  cloud:
    alicloud:
      access-key: LTAI5tA7Qy4dSiQXuiXmit1S
      secret-key: lrQ55pTPC9c0zRRixyOusNNzg1d0e9
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  thymeleaf:
    cache: false

  redis:
    host: 192.168.175.201
    port: 6379
    database: 1
  cache:
    type: redis
logging:
  level:
    com.losca.gulimall.product: debug
server:
  port: 11000
