spring:
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowed-methods: "*"
#            allowed-headers: "*"
      routes:
        - id: product_route
          uri: lb://product
          filters:
            - RewritePath=/api/product/(?<segment>/?.*), /product/$\{segment}
          predicates:
            - Path=/api/product/**
        - id: admin_route
          uri: lb://renren-fast
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}
          predicates:
            - Path=/api/**




