spring:
  cloud:
    alicloud:
      access-key: LTAI5tA7Qy4dSiQXuiXmit1S
      secret-key: lrQ55pTPC9c0zRRixyOusNNzg1d0e9
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
      bucket: losca-gulimall
      sms:
        host: https://gyytz.market.alicloudapi.com
        path: /sms/smsSend
        appcode: 3176ec9bfa9a4f5ba28ea881b3a05010
        smsSignId: 2e65b1bb3d054466b82f0c9d125465e2
        template-id: 908e94ccf08b4476ba6c876d13f084ad
        minute: 5


